baseURL = "https://www.localc.ca"
DefaultContentLanguage = "fr"
languageCode = "en-us"
title = "Local C - Articles promotionnels avec de la valeur"
metaDataFormat = "yaml"
preserveTaxonomyNames = true
RemovePathAccents = true

[permalinks]
  	createurs = "/:slug/"
  	singles = "/:slug/"

[taxonomies]
  category = "categories"
  tag = "tags"
  createur = "createurs"

[Languages]
[Languages.en]
[Languages.en.Taxonomies]
category = "categories"
creator = "creators"

[Languages.fr]
[Languages.fr.Taxonomies]
category = "categories"
createur = "createurs"

